### PR TITLE
Feature Add: Insane Mode

### PR DESCRIPTION
**Pull request by donuts-are-good**
500 as an option in the generator for those who are truly insane and place no value on time.

### CODE REVIEW

**Comment by donuts-are-good** [comment]
Please merge. The world needs this.

**Comment by ngundotra** [comment]
Can you give some examples of renders at 25 steps vs 500 steps?

**Comment by donuts-are-good** [comment]
> Can you give some examples of renders at 25 steps vs 500 steps?

I can do that as soon as this is merged, but no, there is no option available to me at the moment to define a custom number.

**Comment by LePips** [comment]
Instead of these frankly odd-manual insertions, it would probably be better if this was a field instead of a picker. Then, anything could happen.

At the same time, you should be able to run locally for testing instead of waiting for the release.

**Comment by donuts-are-good** [comment]
@LePips that would make a great feature request or pull request. you should do that! 😝

**Comment by donuts-are-good** [comment]
No response? Lame.

**Pull request closed without merging**
