### PR TITLE
feat: :sparkles: add context menu support

### PR DESCRIPTION
**Pull request by piotrski**
Add context menu to save and copy images

image

### CODE REVIEW

**Comment by divamgupta** [comment]
Thanks for the PR. Right now the package.lock.json has not been rebased. Maybe remove that from the PR?

**Comment by piotrski** [comment]
@divamgupta I've just updated `package.lock.json`

**Comment by divamgupta** [comment]
Right now, if you do right click on the burger menu, you see "copy link" . can we disable that?

**Comment by piotrski** [comment]
It should be ok right now :)

**Comment by divamgupta** [comment]
Thanks. Also, I think we should just remove package.lock.json from the PR.

**Comment by Leland** [comment]
This will also fix https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/91 (this PR is really `Add context menus to DiffusionBees` – which is a good thing)

**Pull request merged**
