### PR TITLE
Add text search in history

### PR DESCRIPTION
**Pull request by boredcity**
Resolves the issue https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/216

It would be amazing if you can add the "**HACKTOBERFEST-ACCEPTED**" label to the PR (that way it'll count toward my Hacktoberfest PRs https://hacktoberfest.com/participation/ 😅 )

image

### CODE REVIEW

**Comment by boredcity** [comment]
Hope this seems ok to you.

It would be amazing if you can add the "HACKTOBERFEST-ACCEPTED" label to the PR (that way it'll count toward my Hacktoberfest PRs https://hacktoberfest.com/participation/ 😅 )

**Comment by Leland** [comment]
Any chance of fleshing out the commit beyond "init"? It will add a lot of color in future investigation work :) It also appears your username is not associated with your commit (try clicking your name in https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/pull/220/commits/1ad6bfe02cd345debf97b7bea5301abeb336af01)

**Comment by boredcity** [comment]
> Any chance of fleshing out the commit beyond "init"? It will add a lot of color in future investigation work :) It also appears your username is not associated with your commit (try clicking your name in [1ad6bfe](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/1ad6bfe02cd345debf97b7bea5301abeb336af01))

Yeah, that makes sense :)
Hopefully, both problems should be fixed now.

**Comment by divamgupta** [comment]
Thanks for the PR. This is a useful feature. I will review it shortly.

**Comment by divamgupta** [comment]
I have some comments: 
1) Lets remove extended search rules popover. It can be annoying. You could add a brief description in the docs
2) Could you remove package-lock.json from pr
3) Rn if you search for "   " nothing comes up, maybe trim the text 
4) Maybe add "no search results" when there are no search results

Optional 
5) if possible could you also add pagination in general. just simple next and prev button. (that could be separate PR)

**Pull request closed without merging**
