### PR TITLE
Fix save image path names

### LINKED ISSUE #118: 0.3.0 Save prompt name - can't save image.
0.3.0 - Save with prompt name: unable to save.
Most images can't be saved possibly due to character count limit being exceeded.

Have to manually rename files now to save.

Maybe use the seed number as the file name with versioning, or a combination of first 20 charters + seed?

### LINKED ISSUE #201: Save filename no longer contains prompt in 1.2.0
When saving an image (from anywhere) it now always defaults to `Untitled.png`. Previously (1.1.0) it included the prompt, and if saved via history, the seed as well.

I'd like to see the default filename again be the format `12345-prompt.png`. I guess the prompt needs to be truncated if extremely long and unsupported characters filtered out.

### LINKED ISSUE #210: save images with prompts as file name
This feature was super useful and available in the earlier version but seems to be missing in Version 1.2.0 (0008).

### PR DESCRIPTION
**Pull request by Leland**
Fixes the missing prompt and seed values in default save image boxes. Also ensures the default file name length won't be above OS restrictions, and that multibyte characters like é don't cause problems in the future with the same.

image

Closes #210
Closes #201
Closes #118

### CODE REVIEW

**Comment by Leland** [comment]
https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/blob/62dc0ede757c30f09bc55dcde96e4fb04b0bf0d6/backends/stable_diffusion_tf/diffusionbee_backend.py#L28

~/.diffusionbee/images

**Comment by xirtus** [comment]
sorry if I am being dense, in package contents I don't find "images" what type if file are they?

**Comment by Leland** [comment]
In Finder, press Shift-Cmd-G. Paste in `~/.diffusionbee/images`. Press Enter.

**Comment by xirtus** [comment]
I see it now, thank you for clarifying

**Pull request closed without merging**
