### PR TITLE
No pickle importer

### PR DESCRIPTION
**Pull request by CrudeDiatribe**
Provides a clone of the conversion script, no_pickle_convert_model.py, that uses the also new no_pickle_fake_torch.py; the cloning script is otherwise identical.

no_pickle_fake_torch.py uses [Fickling](https://github.com/trailofbits/fickling) to decompile the pickle file in a .ckpt file. From the decompiled instructions, it enumerates all the Stable Diffusion keys and loads in the relevant weight for each in exactly the same way that fake_torch.py does, returning to the conversion script the dict of weights it is expecting.

Converted .tdict models checksum to the same values as ones done using fake_torch.py and (unsurprisingly) work fine in DBee.

Have successfully tested with 
Stable Diffusion 1.4
Stable Diffusion 1.5 pruned
Classic Animation
Redshift Diffusion
Anything V3
F222 (per issue #307)
PaperCut V1
Mdjrny V4

### CODE REVIEW

**Comment by CrudeDiatribe** [comment]
This importer is currently gagging on the PaperCut-v1 model due to a messy pickle file compared to the ones I used for development and testing. Working on fixing.

**Comment by divamgupta** [comment]
Thanks a lot for your efforts!

**Comment by divamgupta** [comment]
If this works with all SD models, you could replace the code in  `fake_torch` / `convert_model` rather than having separate files.

**Comment by CrudeDiatribe** [comment]
I haven't tried _all_ models yet. I think more people need to use it so we have a better chance at finding models that it doesn't import properly so it can be fixed. It should break loudly on things it doesn't work with so people will at least complain about it. 

Up to you if you want this to be in the same files (replacing or co-existing) with the original code, it felt presumptuous of me to make that decision. I'd be happy to replace the unused function at the bottom of `fake_torch` with my unpickle-less code and then change `convert_model` to only use the unpickling if an optional argument is given to it (e.g. `--unpickle`)

re: integration, this also requires Fickling to be included, which I have no idea how to add to the build.

**Comment by CrudeDiatribe** [comment]
> Up to you if you want this to be in the same files (replacing or co-existing) with the original code, it felt presumptuous of me to make that decision. I'd be happy to replace the unused function at the bottom of fake_torch with my unpickle-less code and then change convert_model to only use the unpickling if an optional argument is given to it (e.g. --unpickle)

Ok, I've done this anyway. This commit has everything in `convert_model.py` and `fake_torch.py`, so the existing call to convert a model will use the decompiling method.

> this also requires Fickling to be included, which I have no idea how to add to the build.

Have not done anything with this requirement.

**Comment by divamgupta** [comment]
@CrudeDiatribe It seems like this fails for ckpt files where there is not 'state_dict'. 
For example in  https://civitai.com/models/3666/protogen-x34-photorealism-official-release in pruned model pickled tensor, all the tensors are outside state_dict . Hence extract_weights_from_checkpoint is not loading anything.

**Comment by CrudeDiatribe** [comment]
> @CrudeDiatribe It seems like this fails for ckpt files where there is not 'state_dict'.
> For example in https://civitai.com/models/3666/protogen-x34-photorealism-official-release in pruned model pickled tensor, all the tensors are outside state_dict . Hence extract_weights_from_checkpoint is not loading anything.

Neat!
I have imported earlier (??) versions of this in the past due to the hype without issue, but I will download this and decompile it and have a go this weekend.

**Comment by CrudeDiatribe** [comment]
OK, I found state_dict problem— the pruned model pickle puts its final weight assignment in the return statement which no model I developed against had. I have fixed fake_torch to account for this ( I think), but the model still won't import because it isn't matching anything in get_model_type() in sd_shapes.

Will go see if I have a SD 2.x model downloaded to decompile but the first shape it is unhappy with is:
Protogen 3.4: "model.diffusion_model.input_blocks.0.0.weight": (320, 9, 3, 3)
sd_shape_consts: "model.diffusion_model.input_blocks.0.0.weight": (320, 4, 3, 3)

**Comment by divamgupta** [comment]
Thank you for looking into this.

it checks shapes against the inpainting  model and the normal stable
diffusion model.
What you printed is checking against inpainting model, Is it not matching
with the normal stable diffusion?

**Comment by CrudeDiatribe** [comment]
> Thank you for looking into this. it checks shapes against the inpainting model and the normal stable diffusion model. What you printed is checking against inpainting model, Is it not matching with the normal stable diffusion?
> […](#)

I should have tried a known-good model first and I would have noticed this complaint even when it likes the model, as it loops over the possibilities (sorry, I should have tried this first to see the differences in output).

First real problem is that this Protogen model lacks the "cond_stage_model.transformer.text_model.embeddings.token_embedding.weight" key, which is a complaint buried at the top of the entire state_dict being written to the terminal so I missed it. 

I checked the .ckpt and it is indeed not there, and your original fake_torch unpicking also gags at this point, so I've at least fixed the decompilation import to be at parity with unpickling. 🙃

**Comment by divamgupta** [comment]
Thanks a lot. Please send a new PR or just paste the patch for the unpickling.

**Comment by CrudeDiatribe** [comment]
Does this work as a patch? Result of git diff with your master branch. 

Can submit a PR with this in the next few days along with removing some unused code. 


```
--- a/backends/model_converter/fake_torch.py
+++ b/backends/model_converter/fake_torch.py
@@ -140,6 +140,9 @@ def examine_pickle(fb0, return_special=False):
   ## 3: this massive line also assigns values to keys, but does so differently
   ## _var2262.update({ 'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.bias': _var2001, [ .... and on  and on ]})
   ##
+  ## 4: in some pruned models, the last line is instead a combination of 2/3 into the final variable:
+  ## result = {'model.diffusion_model.input_blocks.0.0.weight': _var1, 'model.diffusion_model.input_blocks.0.0.bias': _var3, }
+  ##
   ## that's it  
 
   # make some REs to match the above.
@@ -147,6 +150,7 @@ def examine_pickle(fb0, return_special=False):
   re_assign = re.compile('^_var\d+ = \{.*\}$')
   re_update = re.compile('^_var\d+\.update\(\{.*\}\)$')
   re_ordered_dict = re.compile('^_var\d+ = OrderedDict\(\)$')
+  re_result = re.compile('^result = \{.*\}$')
 
   load_instructions = {}
   assign_instructions = AssignInstructions()
@@ -157,7 +161,7 @@ def examine_pickle(fb0, return_special=False):
     if re_rebuild.match(line):
       variable_name, load_instruction = line.split(' = ', 1)
       load_instructions[variable_name] = LoadInstruction(line, variable_name)
-    elif re_assign.match(line):
+    elif re_assign.match(line) or re_result.match(line):
       assign_instructions.parse_assign_line(line)
     elif re_update.match(line):
       assign_instructions.parse_update_line(line)
@@ -184,11 +188,34 @@ class AssignInstructions:
     self.integrated_instructions = {}
     self.collect_special = collect_special;
 
+  def parse_result_line(self, line):
+    garbage, huge_mess = line.split(' = {', 1)
+    assignments = huge_mess.split(', ')
+    del huge_mess
+    assignments[-1] = assignments[-1].strip('}')
+
+    #compile RE here to avoid doing it every loop iteration:
+    re_var = re.compile('^_var\d+$')
+
+    assignment_count = 0
+    for a in assignments:
+      if self._add_assignment(a, re_var):
+        assignment_count = assignment_count + 1
+    if NO_PICKLE_DEBUG:
+      print(f"Added/merged {assignment_count} assignments. Total of {len(self.instructions)} assignment instructions")
+
   def parse_assign_line(self, line):
     # input looks like this:
     # _var2262 = {'model.diffusion_model.input_blocks.0.0.weight': _var1, 'model.diffusion_model.input_blocks.0.0.bias': _var3,\
     #  ...\
     #  'cond_stage_model.transformer.text_model.encoder.layers.3.layer_norm2.weight': _var1999}
+
+    # input looks like the above, but with 'result' in place of _var2262:
+    # result = {'model.diffusion_model.input_blocks.0.0.weight': _var1, ... }
+    #
+    # or also look like: 
+    # result = {'state_dict': _var2314}
+    # ... which will be ignored later
     garbage, huge_mess = line.split(' = {', 1)
     assignments = huge_mess.split(', ')
     del huge_mess
@@ -211,7 +238,7 @@ class AssignInstructions:
     # 'embedding_manager.embedder.transformer.text_model.encoder.layers.6.mlp.fc1': {'version': 1}
     sd_key, fickling_var = assignment.split(': ', 1)
     sd_key = sd_key.strip("'")
-    if re_var.match(fickling_var):
+    if sd_key != 'state_dict' and re_var.match(fickling_var):
       self.instructions[sd_key] = fickling_var
       return True
     elif self.collect_special:
@@ -225,7 +252,8 @@ class AssignInstructions:
         v = v.strip("'")
         special_dict[k] = v
       self.special_instructions[sd_key] = special_dict
-      return False
+
+    return False
 
   def integrate(self, load_instructions):
     unfound_keys = {}
```

**Comment by divamgupta** [comment]
Thanks a lot

**Pull request merged**
