### PR TITLE
Add Electron linter to GitHub Actions

### PR DESCRIPTION
**Pull request by Leland**
Runs `npm run lint` on each PR and merge to `master`. This will run a set of Vue eslint rules against the code, preventing common sense errors from getting merged.

The build executes in seconds, example job here: https://github.com/Leland/diffusionbee-stable-diffusion-ui/actions/runs/3169819178

This PR also fixes the existing errors. All have to do with unused arguments, unused variables, and mixing tabs and spaces.

Finally, this PR introduces an `.editorconfig` file that standardizes the spacing and line ending usage across the repo, and removes all instances of tabbed indents in the electron-app folder.

My hope is this template will spur contributors to add additional actions. It would be great to get a build action created, as well as [integration tests](https://blog.stranianelli.com/how-to-test-electronjs-app-english/) around the app.

### CODE REVIEW

**Comment by Leland** [comment]
@divamgupta any interest in this one? It will help you catch if contributions in PRs have obvious problems

**Comment by Leland** [comment]
@divamgupta starting to get conflicts in this due to age :) Do you have any interest in merging this workflow?

**Comment by divamgupta** [comment]
Hey, thanks for the PR, once the development is in a stable state, we can def add liners, actions and stuff.

**Comment by Leland** [comment]
Fair enough :) (I think this is _more_ helpful while development is not in a stable state, though)

**Pull request closed without merging**
